(* let raw = {|3   4 *)
(* 4   3 *)
(* 2   5 *)
(* 1   3 *)
(* 3   9 *)
(* 3   3 *)
(*   |} *)
(**)
(* let%expect_test "columns" = *)
(*   let list1, list2 = lists_of_input raw in *)
(*   printf "Column 1: %s\n" (list1 |> List.map ~f:Int.to_string |> String.concat ~sep:", "); *)
(*   printf "Column 2: %s\n" (list2 |> List.map ~f:Int.to_string |> String.concat ~sep:", "); *)
(*   [%expect {| *)
(*     Column 1: 3, 4, 2, 1, 3, 3 *)
(*     Column 2: 4, 3, 5, 3, 9, 3 |}] *)
(* ;; *)
